version: '3.8'

services:
  hafizbot:
    build: .
    container_name: hafizbot
    restart: always
    volumes:
      - ./data:/app/data
      - .env:/app/.env
    environment:
      - DATABASE_URL=file:/app/data/memory.db
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
